"""rename department

Revision ID: 5239aabce7c2
Revises: 9637174d438a
Create Date: 2024-04-05 17:06:21.698505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5239aabce7c2'
down_revision = '9637174d438a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments, department')
    # ### end Alembic commands ###
